//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podatki.wtf.Blazor.Resources.Pages.Modals {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExplainDaysOffModal {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExplainDaysOffModal() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Podatki.wtf.Blazor.Resources.Pages.Modals.ExplainDaysOffModal", typeof(ExplainDaysOffModal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Content_Line1 {
            get {
                return ResourceManager.GetString("Content_Line1", resourceCulture);
            }
        }
        
        internal static string Content_Line2 {
            get {
                return ResourceManager.GetString("Content_Line2", resourceCulture);
            }
        }
        
        internal static string Content_Line3 {
            get {
                return ResourceManager.GetString("Content_Line3", resourceCulture);
            }
        }
        
        internal static string Content_Line4 {
            get {
                return ResourceManager.GetString("Content_Line4", resourceCulture);
            }
        }
        
        internal static string Content_Line5 {
            get {
                return ResourceManager.GetString("Content_Line5", resourceCulture);
            }
        }
    }
}
